import React from "react";

const PdfLinks = [
  {
    href: "https://www.hipdf.com/pdf-to-word",
    className: "tool",
    ga360location: "content_2_buttonLink_11",
    imgSrc: "https://images.hipdf.com/images2022/icons/pdf-word.svg",
    imgAlt: "pdf to word",
    title: "PDF to Word",
    desc: "Easily convert PDF to Word document.",
  },
  {
    href: "https://www.hipdf.com/pdf-to-ppt",
    className: "tool",
    ga360location: "content_2_buttonLink_12",
    imgSrc: "https://images.hipdf.com/images2022/icons/PDF-PPT.svg",
    imgAlt: "pdf to PPT",
    title: "PDF to PPT",
    desc: "Convert PDF to Powerpoint online.",
  },
  {
    href: "https://www.hipdf.com/pdf-to-word",
    className: "tool",
    ga360location: "content_2_buttonLink_13",
    imgSrc: "https://images.hipdf.com/images2022/icons/pdf-word.svg",
    imgAlt: "pdf to Excel",
    title: "PDF to Excel",
    desc: "Easily convert PDF to Word document.",
  },
  {
    href: "https://www.hipdf.com/pdf-to-excel",
    className: "tool",
    ga360location: "content_2_buttonLink_14",
    imgSrc: "https://images.hipdf.com/images2022/icons/PDF-JPG.svg",
    imgAlt: "pdf to JPG",
    title: "PDF to JPF",
    desc: "Convert PDF files to a set of optimized JPG, PNG, BMP, GIF ",
  },
  {
    href: "https://www.hipdf.com/pdf-to-text",
    className: "tool",
    ga360location: "content_2_buttonLink_15",
    imgSrc: "https://images.hipdf.com/images2022/icons/PDF-TXT.svg",
    imgAlt: "pdf to TXT",
    title: "PDF to TXT",
    desc: " Convert your PDF to TXT, and extract text from your PDF.",
  },
  {
    href: "https://www.hipdf.com/pdf-to-rtf",
    className: "tool",
    ga360location: "content_2_buttonLink_16",
    imgSrc: "https://images.hipdf.com/images2022/icons/PDF-RTX.svg",
    imgAlt: "pdf to RTF",
    title: "PDF to RTF",
    desc: "Convert PDF to RTF online and free.",
  },
  // {
  //   href: "https://www.hipdf.com/pdf-to-pages",
  //   className: "tool",
  //   ga360location: "content_2_buttonLink_17",
  //   imgSrc: "https://images.hipdf.com/images2022/icons/PDF-Pages.svg",
  //   imgAlt: "pdf to pages",
  //   title: "PDF to pages",
  //   desc: " Convert PDF to Pages on Mac and Windows..",
  // },
  // {
  //   href: "https://www.hipdf.com/pdf-to-html",
  //   className: "tool",
  //   ga360location: "content_2_buttonLink_18",
  //   imgSrc: "https://images.hipdf.com/images2022/icons/pdf-html.svg",
  //   imgAlt: "pdf to html",
  //   title: "PDF to HTML",
  //   desc: "Convert your PDF documents to HTML web page.",
  // },
  // {
  //   href: "https://www.hipdf.com/pdf-to-dxf",
  //   className: "tool",
  //   ga360location: "content_2_buttonLink_19",
  //   imgSrc: "https://images.hipdf.com/images2022/icons/PDF-DXF.svg",
  //   imgAlt: "pdf to dfx",
  //   title: "PDF to DXF",
  //   desc: "The best online tool to convert PDF to DXF online.",
  // },
];

export default PdfLinks;
